version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    cooldown:
      semver-major-days: 90
      semver-minor-days: 45
    groups:
      prod:
        dependency-type: production
        update-types: ["minor", "patch"]
      dev:
        dependency-type: development
        update-types: ["minor", "patch"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: devcontainers
    directory: /
    schedule:
      interval: monthly
