name: Generate docs

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: latest
          registry-url: https://registry.npmjs.org/
      - run: npm run doc
      - run: npm run format
      - uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "chore: generate docs"
          title: "chore: generate docs"
